// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/events-redesign/OpcaoA.tsx": () => import("../components/mockups/events-redesign/OpcaoA.tsx"),
  "./components/mockups/events-redesign/OpcaoB.tsx": () => import("../components/mockups/events-redesign/OpcaoB.tsx")
};
